sudo: required

services:
    - docker

before_install:
    - docker build -t docker-react-dev -f Dockerfile.dev .

script:
    - docker run -e CI=true docker-react-dev npm run test

deploy:
    on:
        branch: master
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "Docker React"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-297436977708"
    bucket_path: "docker-react"
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
